services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./src:/app/src
    user: "${DOCKER_USER_ID:-1000}:${DOCKER_GROUP_ID:-1000}"
    command: uvicorn src.prompt_guard.api.main:app --host 0.0.0.0 --port 8000 --reload
